---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pcf-bosh-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/pcf-bosh-ci
    branch: master
    private_key: {{pcf-bosh-ci_deploy_key}}

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment
    branch: master

- name: cf-acceptance-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-acceptance-tests
    branch: master

- name: p-ert-bosh-experiment
  type: git
  source:
    uri: https://github.com/pivotal-cf/p-ert-bosh-experiment
    branch: master

# github releases
- name: notifications-ui-release
  type: github-release
  source:
    user: pivotal-cf
    repository: notifications-ui-release
    access_token: {{github_releases_access_token}}

- name: cf-autoscaling-release
  type: github-release
  source:
    user: pivotal-cf
    repository: cf-autoscaling-release
    access_token: {{github_releases_access_token}}

- name: console-release
  type: github-release
  source:
    user: pivotal-cf
    repository: console-release
    access_token: {{github_releases_access_token}}

# bosh.io releases
- name: cf-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cf-release

- name: postgres-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/postgres-release

# s3 releases
- name: mysql-monitoring-release
  type: s3
  source:
    bucket: mysql-monitoring-releases
    regexp: final/mysql-monitoring-(\d+\.0).tgz
    access_key_id: {{mysql_releases_access_key_id}}
    secret_access_key: {{mysql_releases_secret_access_key}}

- name: mysql-backup-release
  type: s3
  source:
    bucket: mysql-backup-releases
    regexp: final/mysql-backup-([\d.]+\.0).tgz
    access_key_id: {{mysql_releases_access_key_id}}
    secret_access_key: {{mysql_releases_secret_access_key}}

- name: service-backup-release
  type: pivnet
  source:
    api_token: {{pivnet_api_token}}
    product_slug: service-backups-sdk

- name: minimal-dockerfile
  type: git
  source:
    uri: git@github.com:pivotal-cf/pcf-bosh-ci
    private_key: {{pcf-bosh-ci_deploy_key}}
    paths: [Dockerfile]
    branch: master

- name: minimal-docker-image
  type: docker-image
  source:
    repository: pcfbosh/minimal
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}

- name: terraforming-gcp
  type: git
  source:
    uri: git@github.com:pivotal-cf/pcf-bosh-terraforming-gcp
    private_key: {{pcf-bosh-terraforming-gcp_deploy_key}}
    branch: master

- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment
    branch: master

- name: terraform-state
  type: terraform
  source:
    storage:
      bucket: pcf-bosh-ci
      bucket_path: terraform-environments
      access_key_id: {{gcs_access_key_id}}
      secret_access_key: {{gcs_secret_access_key}}
      endpoint: storage.googleapis.com
  delete_on_failure: true

- name: bosh-state
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: bosh-state.json

- name: bosh-creds
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: bosh-creds.yml

- name: cf-creds
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: cf-creds.yml

- name: cf-cats-config
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: cf-cats-config.json

- name: cf-rats-config
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: cf-rats-config.json

- name: terraform-vars
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: terraform.tfvars.yml

- name: bosh-vars
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: bosh-vars.yml

- name: credhub-release
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: credhub-0.3.0.tgz

- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

jobs:
- name: minimal-docker-image
  public: true
  plan:
  - get: minimal-dockerfile
    trigger: true
  - put: minimal-docker-image
    params:
      build: minimal-dockerfile

- name: terraform-up
  plan:
  - aggregate:
    - get: terraforming-gcp
    - get: terraform-vars
  - put: terraform-state
    params:
      var_file: terraform-vars/terraform.tfvars.yml
      terraform_source: terraforming-gcp
      delete_on_failure: true
      env_name: ol-smokey

- name: deploy-director
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-deployment
    - get: bosh-state
    - get: bosh-creds
    - get: bosh-vars
    - get: credhub-release
    - get: terraform-state
      trigger: true
      passed: [terraform-up]
  - task: deploy-director
    file: pcf-bosh-ci/tasks/deploy-director.yml
    ensure:
      aggregate:
      - put: bosh-state
        params:
          file: new-bosh-state/*
      - put: bosh-creds
        params:
          file: new-bosh-creds/*

- name: upload-cloud-config
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-creds
      trigger: true
      passed: [deploy-director]
  - task: upload-cloud-config
    file: pcf-bosh-ci/tasks/upload-cloud-config.yml

- name: upload-stemcell
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: stemcell
    - get: bosh-creds
      trigger: true
      passed: [deploy-director]
  - task: upload-stemcell
    file: pcf-bosh-ci/tasks/upload-stemcell.yml

- name: deploy-pcf
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: cf-deployment
    - get: p-ert
      resource: p-ert-bosh-experiment
    - get: cf-creds
    - get: service-backup-release
      params:
        globs:
        - "*tgz"
    - get: notifications-ui-release
    - get: mysql-monitoring-release
    - get: cf-autoscaling-release
    - get: mysql-backup-release
    - get: console-release
    - get: postgres-release
      params:
        tarball: true
    - get: cf-release
      params:
        tarball: true
    - get: bosh-creds
      trigger: true
      passed: [upload-cloud-config, upload-stemcell]
  - task: deploy-pcf
    file: pcf-bosh-ci/tasks/deploy-pcf.yml
    ensure:
        put: cf-creds
        params:
          file: new-cf-creds/*

- name: run-cats
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: cf-acceptance-tests
    - get: cf-cats-config
    - get: cf-creds
      trigger: true
      passed: [deploy-pcf]
  - task: enable-diego-docker
    file: pcf-bosh-ci/tasks/enable-diego-docker.yml
  - task: run-cats
    file: pcf-bosh-ci/tasks/run-cats.yml

- name: run-rats
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: cf-acceptance-tests
    - get: cf-rats-config
    - get: cf-deployment
      passed: [deploy-pcf]
    - get: cf-creds
      trigger: true
      passed: [deploy-pcf]
  - task: fetch-routing-release
    file: pcf-bosh-ci/tasks/fetch-routing-release.yml
  - task: run-rats
    file: pcf-bosh-ci/tasks/run-rats.yml