---
platform: linux

image_resource:
  type: docker-image
  source: { repository: pcfbosh/minimal }

inputs:
- name: pcf-bosh-ci
- name: closed-source-releases-zip

outputs:
- name: closed-source-releases

run:
  path: pcf-bosh-ci/tasks/extract-closed-source-releases.sh