---
platform: linux

image_resource:
  type: docker-image
  source: { repository: pcfbosh/minimal }

inputs:
- name: pcf-bosh-ci
- name: cf-deployment

params:
  NAME:

outputs:
- name: stemcell-url

run:
  path: pcf-bosh-ci/tasks/stemcell-url-from-cf-deployment.sh
