---
platform: linux

image_resource:
  type: docker-image
  source: { repository: pcfbosh/minimal }

inputs:
- name: pcf-bosh-ci
- name: bosh-vars-store
- name: terraform-state
- name: release

run:
  path: pcf-bosh-ci/tasks/upload-release.sh
