---
platform: linux

image_resource:
  type: docker-image
  source: { repository: pcfbosh/minimal }

inputs:
- name: pcf-bosh-ci
- name: cloud-config
- name: bosh-creds
- name: terraform-state

params:
  ENV_NAME:

run:
  path: pcf-bosh-ci/tasks/upload-cloud-config.sh
