---
platform: linux

image_resource:
  type: docker-image
  source: { repository: pcfbosh/minimal }

inputs:
- name: pcf-bosh-ci

outputs:
- name: built-project

run:
  path: pcf-bosh-ci/tasks/deploy-director/task.sh