---
platform: linux

image_resource:
  type: docker-image
  source: { repository: pcf-bosh-ci/minimal }

inputs:
- name: pcf-bosh-ci
- name: terraform-state

outputs:
- name: bosh-state

run:
  path: pcf-bosh-ci/tasks/deploy-director/task.sh