resources:
- name: minimal-dockerfile
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-bosh-ci
    paths: [docker/minimal/Dockerfile]
    branch: master

- name: minimal-docker-image
  type: docker-image
  source:
    repository: pcfbosh/minimal
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}

- name: aws-ruby-dockerfile
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-bosh-ci
    paths: [docker/aws-ruby/Dockerfile]
    branch: master

- name: aws-ruby-docker-image
  type: docker-image
  source:
    repository: pcfbosh/aws-ruby
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}

jobs:
- name: minimal-docker-image
  public: true
  plan:
  - get: minimal-dockerfile
    trigger: true
  - put: minimal-docker-image
    params:
      build: minimal-dockerfile/docker/minimal

- name: aws-ruby-docker-image
  public: true
  plan:
  - get: aws-ruby-dockerfile
    trigger: true
  - put: aws-ruby-docker-image
    params:
      build: aws-ruby-dockerfile/docker/aws-ruby
