resources:
- name: minimal-dockerfile
  type: git
  source:
    uri: git@github.com:pivotal-cf/pcf-bosh-ci
    private_key: {{pcf-bosh-ci_deploy_key}}
    paths: [Dockerfile]
    branch: master

- name: minimal-docker-image
  type: docker-image
  source:
    repository: pcfbosh/minimal
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}

jobs:
- name: minimal-docker-image
  public: true
  plan:
  - get: minimal-dockerfile
    trigger: true
  - put: minimal-docker-image
    params:
      build: minimal-dockerfile
