---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:

#########################
# PCF BOSH Repositories #
#########################

- name: pcf-bosh-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-bosh-ci
    branch: master

- name: terraforming-aws
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-bosh-terraforming-aws
    branch: master

- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

- name: cloud-config
  type: git
  source:
    uri: https://github.com/pivotal-cf/p-ert-bosh-experiment
    branch: "1.9"
    paths: [aws/cloud-config.yml]

###################
# CF Repositories #
###################

- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment
    branch: master

#########################
# Pipeline Global State #
#########################

- name: terraform-vars
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: terraform-aws.tfvars.yml

- name: bosh-private-key
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: bosh-private-key

##################
# Pipeline State #
##################

- name: terraform-state
  type: terraform
  source:
    storage:
      bucket: pcf-bosh-ci
      bucket_path: terraform-environments
      access_key_id: {{gcs_access_key_id}}
      secret_access_key: {{gcs_secret_access_key}}
      endpoint: storage.googleapis.com
  delete_on_failure: true

- name: bosh-state
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: '{{env_name}}-bosh-state.json'

- name: bosh-vars-store
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: '{{env_name}}-bosh-vars-store.yml'

jobs:

##################
# Infrastructure #
##################

- name: terraform-up
  plan:
  - aggregate:
    - get: terraforming-aws
      trigger: true
    - get: terraform-vars
      trigger: true
    - get: terraform
      trigger: true
  - put: terraform-state
    params:
      var_file: terraform-vars/terraform-aws.tfvars.yml
      terraform_source: terraforming-aws
      delete_on_failure: true
      env_name: {{env_name}}

- name: deploy-director
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-deployment
      version:
        ref: ccca4c9f7bcdd0f217c8c3adf186648c52b3b137
    - get: bosh-state
    - get: bosh-private-key
    - get: bosh-vars-store
    - get: terraform-state
      trigger: true
      passed: [terraform-up]
  - task: deploy-director
    file: pcf-bosh-ci/tasks/deploy-director-aws.yml
    ensure:
      aggregate:
      - put: bosh-state
        params:
          file: new-bosh-state/*
      - put: bosh-vars-store
        params:
          file: new-bosh-vars-store/*

- name: upload-cloud-config
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: cloud-config
      trigger: true
    - get: bosh-vars-store
      trigger: true
      passed: [deploy-director]
    - get: terraform-state
      trigger: true
      passed: [deploy-director]
  - task: upload-cloud-config
    file: pcf-bosh-ci/tasks/upload-cloud-config-aws.yml
