---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:

#########################
# PCF BOSH Repositories #
#########################

- name: pcf-bosh-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-bosh-ci
    branch: master

- name: cloud-config
  type: git
  source:
    uri: https://github.com/pivotal-cf/p-ert-bosh-experiment
    branch: {{p-ert-branch}}
    paths: [cloud-config.yml]

- name: p-ert-bosh-experiment
  type: git
  source:
    uri: https://github.com/pivotal-cf/p-ert-bosh-experiment
    branch: {{p-ert-branch}}

- name: terraforming-gcp
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-bosh-terraforming-gcp
    branch: master

###################
# CF Repositories #
###################

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment
    branch: master

    # This variable allows users to decide to lock to cf-deployment
    # version 0.0.0 or to float on the latest commit to master. By
    # setting the variable to "tag_filter", cf-deployment will be
    # locked to 0.0.0.
    {{set_to_tag_filter_to_lock_cf_deployment}}: "0\\.0\\.0"

- name: cf-acceptance-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-acceptance-tests
    branch: master

- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment
    branch: master

##############
# PCF Assets #
##############

- name: credhub-release
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: credhub-0.3.0.tgz

- name: closed-source-releases-zip
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: closed-source-releases.zip

######################
# External Resources #
######################

- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

#########################
# Pipeline Global State #
#########################

- name: terraform-vars
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: terraform.tfvars.yml

##################
# Pipeline State #
##################

- name: terraform-state
  type: terraform
  source:
    storage:
      bucket: pcf-bosh-ci
      bucket_path: terraform-environments
      access_key_id: {{gcs_access_key_id}}
      secret_access_key: {{gcs_secret_access_key}}
      endpoint: storage.googleapis.com
  delete_on_failure: true

- name: bosh-state
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: '{{env_name}}-bosh-state.json'

- name: bosh-creds
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: '{{env_name}}-bosh-creds.yml'

- name: cf-creds
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: '{{env_name}}-cf-creds.yml'

jobs:

##################
# Infrastructure #
##################

- name: terraform-up
  plan:
  - aggregate:
    - get: terraforming-gcp
      trigger: true
    - get: terraform-vars
      trigger: true
    - get: terraform
      trigger: true
  - put: terraform-state
    params:
      var_file: terraform-vars/terraform.tfvars.yml
      terraform_source: terraforming-gcp
      delete_on_failure: true
      env_name: {{env_name}}

########
# BOSH #
########

- name: deploy-director
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-deployment
      version:
        ref: ccca4c9f7bcdd0f217c8c3adf186648c52b3b137
    - get: bosh-state
    - get: bosh-creds
    - get: credhub-release
    - get: terraform-state
      trigger: true
      passed: [terraform-up]
  - task: deploy-director
    file: pcf-bosh-ci/tasks/deploy-director.yml
    params:
      GOOGLE_JSON_KEY: {{google_json_key}}
    ensure:
      aggregate:
      - put: bosh-state
        params:
          file: new-bosh-state/*
      - put: bosh-creds
        params:
          file: new-bosh-creds/*

- name: upload-cloud-config
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: cloud-config
      trigger: true
    - get: bosh-creds
      trigger: true
      passed: [deploy-director]
    - get: terraform-state
      trigger: true
      passed: [deploy-director]
  - task: upload-cloud-config
    file: pcf-bosh-ci/tasks/upload-cloud-config.yml

- name: upload-stemcell
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: cf-deployment
      trigger: true
    - get: bosh-creds
      trigger: true
      passed: [deploy-director]
    - get: terraform-state
      passed: [deploy-director]
  - task: stemcell-url-from-cf-deployment
    file: pcf-bosh-ci/tasks/stemcell-url-from-cf-deployment.yml
    params:
      NAME: bosh-google-kvm-ubuntu-trusty-go_agent
  - task: upload-stemcell
    file: pcf-bosh-ci/tasks/upload-stemcell.yml

#################
# Cloud Foundry #
#################

- name: deploy-ert
  serial: true
  serial_groups: [bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: cf-deployment
      trigger: true
      passed: [upload-stemcell]
    - get: p-ert
      resource: p-ert-bosh-experiment
      trigger: true
    - get: cf-creds
    - get: closed-source-releases-zip
    - get: bosh-creds
      trigger: true
      passed: [upload-cloud-config, upload-stemcell]
    - get: terraform-state
      passed: [upload-cloud-config, upload-stemcell]
  - task: extract-closed-source-releases
    file: pcf-bosh-ci/tasks/extract-closed-source-releases.yml
  - task: deploy-ert
    file: pcf-bosh-ci/tasks/deploy-ert.yml
    ensure:
        put: cf-creds
        params:
          file: new-cf-creds/*

###################
# Default Errands #
###################

- name: push-apps-manager
  serial: true
  serial_groups: [bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-creds
      passed: [deploy-ert]
    - get: terraform-state
      passed: [deploy-ert]
    - get: cf-creds
      trigger: true
      passed: [deploy-ert]
    - get: cf-deployment
      passed: [deploy-ert]
  - task: push-apps-manager
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      ERRAND_NAME: push-apps-manager

- name: deploy-notifications
  serial: true
  serial_groups: [bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-creds
      passed: [deploy-ert]
    - get: terraform-state
      passed: [deploy-ert]
    - get: cf-creds
      trigger: true
      passed: [deploy-ert]
    - get: cf-deployment
      passed: [deploy-ert]
  - task: deploy-notifications
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      ERRAND_NAME: deploy-notifications

- name: deploy-notifications-ui
  serial: true
  serial_groups: [bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-creds
      passed: [deploy-notifications]
    - get: terraform-state
      passed: [deploy-notifications]
    - get: cf-creds
      trigger: true
      passed: [deploy-notifications]
    - get: cf-deployment
      passed: [deploy-notifications]
  - task: deploy-notifications-ui
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      ERRAND_NAME: deploy-notifications-ui

- name: deploy-autoscaling
  serial: true
  serial_groups: [bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-creds
      passed: [deploy-ert]
    - get: terraform-state
      passed: [deploy-ert]
    - get: cf-creds
      trigger: true
      passed: [deploy-ert]
    - get: cf-deployment
      passed: [deploy-ert]
  - task: deploy-autoscaling
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      ERRAND_NAME: deploy-autoscaling

- name: autoscaling-register-broker
  serial: true
  serial_groups: [bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-creds
      passed: [deploy-autoscaling]
    - get: terraform-state
      passed: [deploy-autoscaling]
    - get: cf-creds
      trigger: true
      passed: [deploy-autoscaling]
    - get: cf-deployment
      passed: [deploy-autoscaling]
  - task: autoscaling-register-broker
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      ERRAND_NAME: autoscaling-register-broker

- name: push-pivotal-account
  serial: true
  serial_groups: [bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-creds
      passed: [deploy-ert]
    - get: terraform-state
      passed: [deploy-ert]
    - get: cf-creds
      trigger: true
      passed: [deploy-ert]
    - get: cf-deployment
      passed: [deploy-ert]
  - task: push-pivotal-account
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      ERRAND_NAME: push-pivotal-account

####################
# Recovery Errands #
####################

- name: mysql-bootstrap
  serial: true
  serial_groups: [bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-creds
      passed: [deploy-ert]
    - get: terraform-state
      passed: [deploy-ert]
    - get: cf-creds
      passed: [deploy-ert]
    - get: cf-deployment
      passed: [deploy-ert]
  - task: mysql-bootstrap
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      ERRAND_NAME: mysql-bootstrap

- name: mysql-rejoin-unsafe
  serial: true
  serial_groups: [bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-creds
      passed: [deploy-ert]
    - get: terraform-state
      passed: [deploy-ert]
    - get: cf-creds
      passed: [deploy-ert]
    - get: cf-deployment
      passed: [deploy-ert]
  - task: mysql-rejoin-unsafe
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      ERRAND_NAME: mysql-rejoin-unsafe

#########
# Tests #
#########

- name: smoke-tests
  serial_groups: [bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-creds
      passed: &errands [push-apps-manager, deploy-notifications-ui, autoscaling-register-broker]
    - get: cf-creds
      trigger: true
      passed: *errands
    - get: terraform-state
      passed: *errands
  - task: run-smoke-tests
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      ERRAND_NAME: smoke-tests

- name: run-cats
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: cf-acceptance-tests
      version: {ref: 0e6b46fc44ecc5da7735fc2a48213de0e49b4dbf}
    - get: cf-creds
      trigger: true
      passed: *errands
    - get: terraform-state
      passed: *errands
  - task: enable-diego-docker
    file: pcf-bosh-ci/tasks/enable-diego-docker.yml
  - task: run-cats
    file: pcf-bosh-ci/tasks/run-cats.yml

- name: run-rats
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: cf-acceptance-tests
    - get: cf-deployment
      passed: *errands
    - get: cf-creds
      trigger: true
      passed: *errands
    - get: terraform-state
      passed: *errands
  - task: fetch-routing-release
    file: pcf-bosh-ci/tasks/fetch-routing-release.yml
  - task: run-rats
    file: pcf-bosh-ci/tasks/run-rats.yml
