---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:

#########################
# PCF BOSH Repositories #
#########################

- name: terraforming-aws
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-bosh-terraforming-aws
    branch: master

- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

#########################
# Pipeline Global State #
#########################

- name: terraform-vars
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: terraform-aws.tfvars.yml

##################
# Pipeline State #
##################

- name: terraform-state
  type: terraform
  source:
    storage:
      bucket: pcf-bosh-ci
      bucket_path: terraform-environments
      access_key_id: {{gcs_access_key_id}}
      secret_access_key: {{gcs_secret_access_key}}
      endpoint: storage.googleapis.com
  delete_on_failure: true

jobs:

##################
# Infrastructure #
##################

- name: terraform-up
  plan:
  - aggregate:
    - get: terraforming-aws
      trigger: true
    - get: terraform-vars
      trigger: true
    - get: terraform
      trigger: true
  - put: terraform-state
    params:
      var_file: terraform-vars/terraform-aws.tfvars.yml
      terraform_source: terraforming-aws
      delete_on_failure: true
      env_name: {{env_name}}
