---
platform: linux

image_resource:
  type: docker-image
  source: { repository: pcfbosh/minimal }

inputs:
- name: pcf-bosh-ci
- name: routing-release
- name: cf-rats-config

run:
  path: pcf-bosh-ci/tasks/run-rats/task.sh
