---
platform: linux

image_resource:
  type: docker-image
  source: { repository: pcfbosh/minimal }

inputs:
- name: pcf-bosh-ci
- name: cf-acceptance-tests
- name: cf-cats-config

run:
  path: pcf-bosh-ci/tasks/run-cats/task.sh
